### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by reinzor** [piappl/robotic-map#1]
Hi,

I tried to make the ROS package but I am running into some issues.

Making libmapwidget.so seems to work fine with:

```
    ./make-map.sh /opt/Qt/5.7/gcc_64/lib/cmake/
```

The libmapwidget.so is installed using make install. However, when I try to compile the ros-package rosmapinterface, linking failes due to missing references in `/usr/local/lib/libmarblewidget-qt5.so.23` in the libmapwidget.so

```
    //usr/local/lib/libmarblewidget-qt5.so.23: undefined reference to `QWidget::closeEvent(QCloseEvent*)@Qt_5'
    //usr/local/lib/libmarblewidget-qt5.so.23: undefined reference to `QReadWriteLock::~QReadWriteLock()@Qt_5'
    ...
```

I am running Xenial with Kinetic.

Any ideas?

**Comment by adamdbrw** [comment]
Hi,

Thanks for report.

It looks like there is a problem with Qt version (too new, possibly not supported in our marble fork). I will take a look at it, possibly updating the fork will fix the issue. The lib was tested up to Qt 5.5. and it's time to verify it for newer versions.

**Comment by adamdbrw** [comment]
I've updated the library to work with new Marble (which supports) Qt5.7. Let me know if it works for you now.
You need to clear your marble dir (as per script build ~/marble) before you proceed - clean build is highly recommended

**Comment by reinzor** [comment]
I tried to make the map again now but it does not seem to work:

```
    ./make-map.sh /opt/Qt/5.7/gcc_64/lib/cmake
```

Errror:

```
    /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:44:0: note: this is the location of the previous definition
     #define QT_VERSION_STR   "5.5.1"
     ^
    CMakeFiles/merge_ts_po.dir/merge_ts_po.cpp.o:(.qtversion[qt_version_tag]+0x0): undefined reference to `qt_version_tag'
    collect2: error: ld returned 1 exit status
    make[2]: *** [data/lang/merge_ts_po] Error 1
    make[1]: *** [data/lang/CMakeFiles/merge_ts_po.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    In file included from /opt/Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h:44:0,
                     from /opt/Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h:53,
                     from /opt/Qt/5.7/gcc_64/include/QtCore/qatomic.h:46,
                     from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1104,
                     from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtGlobal:1,
                     from /home/rein/marble/source/src/lib/astro/astrolib_export.h:16,
                     from /home/rein/marble/source/src/lib/astro/attlib.h:23,
                     from /home/rein/marble/source/src/lib/astro/eclsolar.h:14,
                     from /home/rein/marble/source/src/lib/astro/eclsolar.cpp:34:
```

**Comment by adamdbrw** [comment]
It looks like it's not a clean build: 
#define QT_VERSION_STR   "5.5.1" indicates that even though you are building with QT 5.7, there is a QT 5.5.1 in your path somewhere. 
There is nothing wrong with Marble or the map library in error you've posted. 

Make sure your paths are ok and that you are building in a clear env. (remove ~/marble and clear ~/robotic-map)

**Comment by reinzor** [comment]
You are right; but the error was due to the following:

```
    $ ./make-map.sh /opt/Qt/5.7/gcc_64/lib/cmake/
    ****Fetching marble from repository
    Cloning into '/home/rein/marble/source'...
    remote: Counting objects: 134846, done.
    remote: Compressing objects: 100% (34066/34066), done.
    remote: Total 134846 (delta 109591), reused 123415 (delta 100192)
    Receiving objects: 100% (134846/134846), 104.52 MiB | 2.88 MiB/s, done.
    Resolving deltas: 100% (109591/109591), done.
    Checking connectivity... done.
    ****git update and checkout to supported version
    Fetching origin
    Note: checking out 'v15.11.80'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    HEAD is now at a7f4f70... bring back support for Dr. Konqui
    ****Applying patch
    error: patch failed: src/lib/marble/CMakeLists.txt:562
    error: src/lib/marble/CMakeLists.txt: patch does not apply
```

**Comment by adamdbrw** [comment]
Yes, it's my bad. I've missed one file in the patch, don't know how. It didn't update Marble properly.
Should be working now (clean build)

**Comment by reinzor** [comment]
Now it starts compiling but fails due to a missing reference:

```
    /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5.5.1: undefined reference to `QWindowSystemInterface::registerTouchDevice(QTouchDevice*)'
```

Thanks again for your support!

**Comment by adamdbrw** [comment]
Well, there's Qt 5.5.1 again - there's the same problem. You are using headers from Qt 5.7 and library from 5.5. Probably 5.7 added/changed this registerTouchDevice function, and the compiler can't find it in the old library. That's again purely a Qt/environment problem. 

All I can say is that on my machine, there is no issue like this with clean build.

Please let me know if you progressed!

**Comment by reinzor** [comment]
I changed the marble cmake:

```
    #######################################################
    # Find Qt dependencies        

    # Minimum Qt version
    set(REQUIRED_QT_VERSION 5.7.0)
```

Now it seems to resolve to the proper qt library and linking is ok. Still weird that it finds that library while the cmake prefix path is set.

Now I am at the next error:

```
    In file included from /home/rein/robotic-map/map/RoboticsMap.h:6:0,
                     from /home/rein/robotic-map/map/MapFactory.cpp:9:
    /usr/local/include/marble/MarbleQuickItem.h:14:39: fatal error: marble_declarative_export.h: No such file or directory
    compilation terminated.
```

What QT version did you use for your compilation, I will try that one then .. Or what do you suggest?

Thanks!

**Comment by adamdbrw** [comment]
Hey, I am looking into it right now..

**Comment by adamdbrw** [comment]
All right, looks like the new version of Marble had a regression (lost support for declarative through removing the said header, marble_declarative_export.h). It worked for me, because the header was still there in my /usr/local/include. I've fixed the issue and tried an entirely clean build (all .h and libs purged as well). Should work for you now. 

Sorry for all the inconvienience, porting the map to new Marble proved to cause way more trouble then I expected. Hope it works for you now. Please let me know.

**Comment by adamdbrw** [comment]
Is this issue solved for you?

**Comment by reinzor** [comment]
Hi Adam,

Sorry that I didn't come back on this. Just gave it a shot again and it it compiling now :). ROS was first using a different version of QT, by explicitly setting the cmake prefix path, it was solved. 

Thanks for your help!
